### ISSUE TITLE
Artifact not found on the snapshot repository.

### ISSUE THREAD

**Issue by devwckd** [DevNatan/yoki#60]
The artifact listed on the README is not working, I've browsed the repository to see if it was perhaps a DNS issue, but it seems to be missing, the folder `me/devnatan` does not exist.

```
repositories {
    maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")
}

dependencies {
    implementation("me.devnatan:yoki:0.0.1-SNAPSHOT")
}
```

**Comment by DevNatan** [comment]
Fixed in v0.1.1 👍🏽
